version: "3.9"
services:
  mongo:
    build:
      context: "./src"
      args:
        - "MONGO_VERSION=latest"
    volumes:
      - "./test/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./test:/test"
    ports:
      - "27017:27017"
