#!/usr/bin/env bash

set -eux

mongod \
  --configsvr \
  --replSet config \
  --dbpath /var/lib/sharded-mongo/mongod-config \
  --bind_ip ::,0.0.0.0 \
  --port 27019 \
  --fork \
  --logpath /var/log/mongod-config.log

wait-for localhost:27019
mongosh --eval 'rs.initiate({_id: "config", configsvr: true, members: [{ _id : 0, host : "localhost:27019" }]})' localhost:27019

mongod \
  --shardsvr \
  --replSet shard \
  --dbpath /var/lib/sharded-mongo/mongod-shard \
  --bind_ip ::,0.0.0.0 \
  --port 27018 \
  --fork \
  --logpath /var/log/mongod-shard.log

wait-for localhost:27018
mongosh --eval 'rs.initiate({_id: "shard", members: [{ _id : 0, host : "localhost:27018" }]})' localhost:27018

mongos \
  --configdb config/localhost:27019 \
  --bind_ip ::,0.0.0.0 \
  --port 27017 \
  --fork \
  --logpath /var/log/mongos.log

wait-for localhost:27017
mongosh --eval 'sh.addShard("shard/localhost:27018")' localhost:27017
mongosh --eval "sh.enableSharding(\"${SHARDED_DATABASE}\")" localhost:27017

exec tail -f /var/log/mongos.log
