name: CI / 4.4

on:
  pull_request:
    paths:
      - .github/workflows/ci-4-4.yaml
      - src/4.4/**
  push:
    paths:
      - .github/workflows/ci-4-4.yaml
      - src/4.4/**
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-release:
    uses: ./.github/workflows/reusable--test-and-release.yaml
    with:
      version: "4.4"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
